import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Image from "next/image";
import { redirect } from "next/navigation";
import Link from "next/link";
import LogoutWithGoogle from "@/components/Buttons/LogoutWithGoogle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ClientPageLayout({ children }) {
    const session = await getServerSession(authOptions);

    if(!session){
        redirect('/');
    }
  return (
    <html lang="en">
      <body className={inter.className}>
         <main className="flex min-h-screen">
             <aside className="bg-blue-100 max-w-md p-4">
                aside stuff
                <div>
                <Image alt={'profile'} src={session.user.image} width={64} height={48}
                />
                </div>
                <nav className="flex flex-col text-center mt-8 gap-4">
                   <Link href={'/account'}><span>My Card</span></Link>
                   <Link href={'/analytics'}><span>Analytics</span></Link>
                   {/* <button type="button" className="flex gap-4" onClick={()=>{}}>
                    <span>Logout</span>
                   </button> */}
                   <LogoutWithGoogle className={'flex gap-4 items-center'}/>
                   <Link href={'/'}>Home</Link>
                </nav>
             </aside>
             <div className="grow">
               <div className="bg-white shadow w-full m-4 p-4">
               {children}
               </div>
                 
             </div>
         </main>
      </body>
    </html>
  );
}
