import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import Image from "next/image";
import { redirect } from "next/navigation";
import Link from "next/link";
import LogoutWithGoogle from "@/components/Buttons/LogoutWithGoogle";
import ClientPageAside from "@/components/layouts/ClientPageAside";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ClientPageLayout({ children }) {
    const session = await getServerSession(authOptions);

    if(!session){
        redirect('/');
    }
  return (
    <html lang="en">
      <body className={inter.className}>
         <main className="flex min-h-screen">
             <aside className="bg-blue-100 max-w-md p-4">
                aside stuff
                <div>
                <Image alt={'profile'} src={session.user.image} width={64} height={48}
                />
                </div>
                <ClientPageAside/>
             </aside>
             <div className="grow">
               <div className="bg-white shadow w-full m-4 p-4">
               {children}
                   <Toaster/>
               </div>
                 
             </div>
         </main>
      </body>
    </html>
  );
}
